-- DecodeLabs Data Analytics Internship
-- Project 3: SQL Data Analysis
-- Table: orders (1,200 cleaned e-commerce order records)

-- Q1: List all orders placed using 'Cash' as the payment method
SELECT OrderID, Date, Product, Quantity, TotalPrice, PaymentMethod
FROM orders
WHERE PaymentMethod = 'Cash'
ORDER BY Date
LIMIT 15;

-- Q2: Find the 10 highest-value orders
SELECT OrderID, Date, Product, CustomerID, TotalPrice
FROM orders
ORDER BY TotalPrice DESC
LIMIT 10;

-- Q3: Count how many orders were placed for each product
SELECT Product, COUNT(*) AS TotalOrders
FROM orders
GROUP BY Product
ORDER BY TotalOrders DESC;

-- Q4: Find total revenue generated by each payment method
SELECT PaymentMethod, SUM(TotalPrice) AS TotalRevenue
FROM orders
GROUP BY PaymentMethod
ORDER BY TotalRevenue DESC;

-- Q5: Find the average order value for each referral source
SELECT ReferralSource, ROUND(AVG(TotalPrice), 2) AS AvgOrderValue, COUNT(*) AS TotalOrders
FROM orders
GROUP BY ReferralSource
ORDER BY AvgOrderValue DESC;

-- Q6: Find products with an average order value greater than 1000 (using HAVING)
SELECT Product, ROUND(AVG(TotalPrice), 2) AS AvgOrderValue
FROM orders
GROUP BY Product
HAVING AVG(TotalPrice) > 1000
ORDER BY AvgOrderValue DESC;

-- Q7: Get order count, total revenue, and average order value for each order status
SELECT OrderStatus, COUNT(*) AS TotalOrders, SUM(TotalPrice) AS TotalRevenue,
       ROUND(AVG(TotalPrice), 2) AS AvgOrderValue
FROM orders
GROUP BY OrderStatus
ORDER BY TotalRevenue DESC;

-- Q8: Find all orders placed in the year 2024
SELECT OrderID, Date, Product, TotalPrice
FROM orders
WHERE Date LIKE '2024%'
ORDER BY Date
LIMIT 15;

-- Q9: Find orders where a coupon was NOT used
SELECT OrderID, Date, Product, CouponCode, TotalPrice
FROM orders
WHERE CouponCode = 'No Coupon'
ORDER BY TotalPrice DESC
LIMIT 15;

-- Q10: Find monthly revenue trend (year-month) sorted chronologically
SELECT SUBSTR(Date, 1, 7) AS Month, COUNT(*) AS TotalOrders, SUM(TotalPrice) AS TotalRevenue
FROM orders
GROUP BY Month
ORDER BY Month;

